-- 001-schema: Verify migrated schema and table structure
-- Generated by db-migration agent during Phase 3 validation

BEGIN;
SELECT plan(20);

-- Schema existence (4 application schemas)
SELECT has_schema('warehouse', 'Schema warehouse should exist');
SELECT has_schema('purchasing', 'Schema purchasing should exist');
SELECT has_schema('sales', 'Schema sales should exist');
SELECT has_schema('application', 'Schema application should exist');

-- Core tables existence (16 key tables)
SELECT has_table('warehouse', 'stock_items', 'Table warehouse.stock_items should exist');
SELECT has_table('warehouse', 'stock_item_holdings', 'Table warehouse.stock_item_holdings should exist');
SELECT has_table('warehouse', 'stock_item_transactions', 'Table warehouse.stock_item_transactions should exist');
SELECT has_table('warehouse', 'cold_room_temperatures', 'Table warehouse.cold_room_temperatures should exist');
SELECT has_table('warehouse', 'colors', 'Table warehouse.colors should exist');

SELECT has_table('sales', 'orders', 'Table sales.orders should exist');
SELECT has_table('sales', 'order_lines', 'Table sales.order_lines should exist');
SELECT has_table('sales', 'invoices', 'Table sales.invoices should exist');
SELECT has_table('sales', 'invoice_lines', 'Table sales.invoice_lines should exist');
SELECT has_table('sales', 'customers', 'Table sales.customers should exist');
SELECT has_table('sales', 'customer_transactions', 'Table sales.customer_transactions should exist');

SELECT has_table('purchasing', 'suppliers', 'Table purchasing.suppliers should exist');
SELECT has_table('purchasing', 'purchase_orders', 'Table purchasing.purchase_orders should exist');
SELECT has_table('purchasing', 'purchase_order_lines', 'Table purchasing.purchase_order_lines should exist');

SELECT has_table('application', 'people', 'Table application.people should exist');
SELECT has_table('application', 'cities', 'Table application.cities should exist');

SELECT * FROM finish();
ROLLBACK;
