-- 002-functions: Verify migrated PL/pgSQL functions exist with correct signatures
-- Generated by db-migration agent during Phase 3 validation

BEGIN;
SELECT plan(8);

-- Warehouse functions
SELECT has_function(
  'warehouse',
  'get_stock_items_paginated',
  ARRAY['integer', 'integer'],
  'Function get_stock_items_paginated(page_size, page_number) should exist'
);

SELECT has_function(
  'warehouse',
  'get_stock_item_by_id',
  ARRAY['integer'],
  'Function get_stock_item_by_id(item_id) should exist'
);

SELECT has_function(
  'warehouse',
  'update_stock_item_holdings',
  ARRAY['integer', 'integer'],
  'Function update_stock_item_holdings(item_id, quantity_change) should exist'
);

SELECT has_function(
  'warehouse',
  'search_stock_items',
  ARRAY['text', 'integer'],
  'Function search_stock_items(search_text, max_results) should exist'
);

-- Sales functions
SELECT has_function(
  'sales',
  'insert_customer_order',
  ARRAY['integer', 'integer', 'date', 'jsonb'],
  'Function insert_customer_order(customer_id, salesperson_id, delivery_date, order_lines) should exist'
);

SELECT has_function(
  'sales',
  'invoice_customer_orders',
  ARRAY['integer', 'integer'],
  'Function invoice_customer_orders(order_id, invoiced_by) should exist'
);

-- Integration functions
SELECT has_function(
  'integration',
  'get_city_updates',
  ARRAY['timestamptz', 'timestamptz'],
  'Function get_city_updates(last_cutoff, new_cutoff) should exist'
);

-- Sequence functions
SELECT has_function(
  'sequences',
  'reseed_all_sequences',
  'Function reseed_all_sequences() should exist'
);

SELECT * FROM finish();
ROLLBACK;
