-- 003-business-logic: Verify business rules are preserved in migrated functions
-- Generated by db-migration agent during Phase 3 validation

BEGIN;
SELECT plan(7);

-- Test 1: Stock reduction below zero should fail
SELECT throws_ok(
  $$SELECT warehouse.update_stock_item_holdings(1, -999999)$$,
  NULL,
  'Reducing stock below zero should raise an exception'
);

-- Test 2: Valid stock reduction should succeed
SELECT lives_ok(
  $$SELECT warehouse.update_stock_item_holdings(1, -1)$$,
  'Reducing stock by 1 should succeed'
);

-- Test 3: Pagination returns expected number of rows
SELECT results_eq(
  $$SELECT count(*)::integer FROM warehouse.get_stock_items_paginated(5, 1)$$,
  5,
  'Paginated query with page_size=5 should return 5 rows'
);

-- Test 4: Point lookup returns exactly one row
SELECT results_eq(
  $$SELECT count(*)::integer FROM warehouse.get_stock_item_by_id(1)$$,
  1,
  'Looking up item by ID should return exactly 1 row'
);

-- Test 5: Search returns results for known item
SELECT isnt_empty(
  $$SELECT * FROM warehouse.search_stock_items('USB', 10)$$,
  'Searching for USB should return at least one stock item'
);

-- Test 6: Insert order creates order with lines
SELECT lives_ok(
  $$SELECT * FROM sales.insert_customer_order(
      1, 1, CURRENT_DATE + 7,
      '[{"stock_item_id": 1, "quantity": 2, "unit_price": 10.00, "description": "Test item"}]'::jsonb
  )$$,
  'Inserting a customer order should succeed'
);

-- Test 7: Non-existent stock item in holdings should raise error
SELECT throws_ok(
  $$SELECT warehouse.update_stock_item_holdings(999999, 1)$$,
  NULL,
  'Updating holdings for non-existent item should raise an exception'
);

SELECT * FROM finish();
ROLLBACK;
